"""
DVC parameters for training pipeline configuration.
"""

data_preparation:
  dataset_name: "training_corpus_v2"
  train_split: 0.8
  validation_split: 0.2
  preprocessing:
    tokenization: true
    normalization: true
    max_length: 512
    vocab_size: 50000

model_training:
  model_type: "transformer"
  architecture:
    layers: 12
    hidden_size: 768
    attention_heads: 12
    intermediate_size: 3072
  
  training:
    learning_rate: 0.0001
    batch_size: 32
    epochs: 10
    warmup_steps: 1000
    weight_decay: 0.01
    gradient_clipping: 1.0
    
  optimization:
    optimizer: "adamw"
    scheduler: "linear_warmup"
    early_stopping: true
    patience: 3
    
  checkpointing:
    save_steps: 500
    save_total_limit: 3
    evaluation_strategy: "steps"
    eval_steps: 250

evaluation:
  metrics:
    - accuracy
    - f1_score
    - precision
    - recall
    - bleu_score
    - perplexity
  
  thresholds:
    min_accuracy: 0.8
    min_f1_score: 0.75
    
  test_datasets:
    - "validation_set"
    - "test_set"
    - "benchmark_dataset"

deployment:
  environment: "staging"
  scaling:
    min_replicas: 2
    max_replicas: 10
    target_cpu_utilization: 70
  
  model_serving:
    framework: "transformers"
    batch_size: 16
    max_batch_delay_ms: 100
    
  monitoring:
    enable_logging: true
    log_level: "INFO"
    metrics_collection: true
