server:
  host: 0.0.0.0
  port: 8000
  debug: false

database:
  url: postgresql://user:password@localhost:5432/lm_training_db
  pool_size: 20
  max_overflow: 30

redis:
  url: redis://localhost:6379/0
  max_connections: 10

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: lm_training_experiments

dvc:
  remote: s3://your-bucket/dvc-storage
  cache_dir: .dvc/cache

monitoring:
  metrics_collection_interval: 30  # seconds
  drift_detection_threshold: 0.1
  prometheus_port: 9090

training:
  max_concurrent_jobs: 3
  checkpoint_interval: 100  # steps
  auto_retry_failed_jobs: true
  max_retries: 3

automation:
  enable_drift_response: true
  reinforcement_schedule_delay: 3600  # seconds
  health_check_interval: 300  # seconds

logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  file_rotation_size: 10485760  # 10MB
  file_backup_count: 5

paths:
  data_dir: data
  model_dir: models
  experiment_dir: experiments
  log_dir: logs
  temp_dir: temp
